
[functions.select-daily-stocks]
enabled = true
verify_jwt = true
entrypoint = "./functions/select-daily-stocks/index.ts"


[functions.calculate-rankings]
enabled = true
verify_jwt = true
entrypoint = "./functions/calculate-rankings/index.ts"

[functions.fetch-market-news-periodically]
enabled = true
verify_jwt = true
entrypoint = "./functions/fetch-market-news-periodically/index.ts"

[functions.fetch-news-summary]
enabled = true
verify_jwt = true
entrypoint = "./functions/fetch-news-summary/index.ts"

[functions.process-daily-results]
enabled = true
verify_jwt = true
entrypoint = "./functions/process-daily-results/index.ts"

[functions.update-krx-stocks]
enabled = true
verify_jwt = true
entrypoint = "./functions/update-krx-stocks/index.ts"

[functions.update-krx-top-100]
enabled = true
verify_jwt = true
entrypoint = "./functions/update-krx-top-100/index.ts"

[functions.update-naver-stocks]
enabled = true
verify_jwt = true
entrypoint = "./functions/update-naver-stocks/index.ts"

[functions.naver-userinfo-proxy]
enabled = true
verify_jwt = false
entrypoint = "./functions/naver-userinfo-proxy/index.ts"
