
[functions.select-daily-stocks]
enabled = true
verify_jwt = true
import_map = "./functions/select-daily-stocks/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/select-daily-stocks/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/select-daily-stocks/*.html" ]

[functions.transfer-hall-of-fame]
enabled = true
verify_jwt = true
import_map = "./functions/transfer-hall-of-fame/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/transfer-hall-of-fame/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/transfer-hall-of-fame/*.html" ]
