[variables]
    NIXPACKS_NODE_VERSION = "20"
    NIXPACKS_NO_CI = "1"

[phases.setup]
    nixPkgs = ["nodejs_20", "python3", "pkg-config"]

[phases.install]
    dependsOn = ["setup"]
    cmds = ["rm -f package-lock.json", "npm install --legacy-peer-deps --ignore-scripts", "npm install --legacy-peer-deps"]
